#Steering Action

#Goal
int32 robot_id
float32 start_x
float32 start_y
float32 goal_x
float32 goal_y
float32 goal_vel_x
float32 goal_vel_y
float32 orient_rad
Hint[]  hints
---
#Result
int8 result
---
#Feedback
int32 status
