#Nav Request
Vector2f start
Vector2f goal
Vector2f goalSpeed 		# Ignored for now. (X-velocity, Y-velocity) in m/s
float64 goalOrientation 	# Ignored for now. In radians.
Hint[] hints
---
#Nav Response
Vector2f[] path
int8 flags
